#NAO REMOVER --> RESPONSAVEL POR COLOCAR O CADEADO NA URL
RewriteEngine On
RewriteCond %{HTTPS} off
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
#NAO REMOVER --> RESPONSAVEL POR COLOCAR O CADEADO NA URL
